### ISSUE TITLE
Installation on Mac M2

### ISSUE THREAD

**Issue by philmar1** [colomemaria/epiScanpy#137]
Hello, I got the following error while trying to install episcanpy on mac with the following config:
- MacOS Ventura 13.4
- Model: M2 Max

Collecting episcanpy
  Using cached episcanpy-0.4.0.tar.gz (50.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5f/wd12d4k54y92nf_37yzs57wc0000gn/T/pip-install-bos65vr8/episcanpy_34180352814c4e248866de19a15909cb/setup.py", line 9, in <module>
          from episcanpy import __author__, __email__
        File "/private/var/folders/5f/wd12d4k54y92nf_37yzs57wc0000gn/T/pip-install-bos65vr8/episcanpy_34180352814c4e248866de19a15909cb/episcanpy/__init__.py", line 3, in <module>
          from .utils import check_versions, annotate_doc_types
        File "/private/var/folders/5f/wd12d4k54y92nf_37yzs57wc0000gn/T/pip-install-bos65vr8/episcanpy_34180352814c4e248866de19a15909cb/episcanpy/utils.py", line 17, in <module>
          from . import settings
        File "/private/var/folders/5f/wd12d4k54y92nf_37yzs57wc0000gn/T/pip-install-bos65vr8/episcanpy_34180352814c4e248866de19a15909cb/episcanpy/settings.py", line 77, in <module>
          import scanpy as sc
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/scanpy/__init__.py", line 6, in <module>
          from ._utils import check_versions
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/scanpy/_utils/__init__.py", line 21, in <module>
          from anndata import AnnData, __version__ as anndata_version
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/anndata/__init__.py", line 7, in <module>
          from ._core.anndata import AnnData
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/anndata/_core/anndata.py", line 27, in <module>
          from .raw import Raw
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/anndata/_core/raw.py", line 10, in <module>
          from .index import _normalize_index, _subset, unpack_index, get_vector
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/anndata/_core/index.py", line 10, in <module>
          from ..compat import AwkArray, DaskArray, Index, Index1D
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/anndata/compat/__init__.py", line 69, in <module>
          from dask.array import Array as DaskArray
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/dask/array/__init__.py", line 2, in <module>
          from dask.array import backends, fft, lib, linalg, ma, overlap, random
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/dask/array/backends.py", line 6, in <module>
          from dask.array.core import Array
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/dask/array/core.py", line 63, in <module>
          from dask.sizeof import sizeof
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/dask/sizeof.py", line 264, in <module>
          _register_entry_point_plugins()
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/dask/sizeof.py", line 254, in _register_entry_point_plugins
          for entry_point in importlib_metadata.entry_points(group="dask.sizeof"):
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 933, in entry_points
          return EntryPoints(eps).select(**params)
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 930, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/importlib_metadata/_py39compat.py", line 18, in normalized_name
          return dist._normalized_name
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 778, in _normalized_name
          or super()._normalized_name
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 445, in _normalized_name
          return Prepared.normalize(self.name)
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 700, in normalize
          return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
        File "/Users/philippemartin/miniconda3/envs/scenicplus/lib/python3.8/re.py", line 210, in sub
          return _compile(pattern, flags).sub(repl, string, count)
      TypeError: expected string or bytes-like object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

Any clue please ?

**Comment by zhaosw001** [comment]
i've met this bug so as
