### ISSUE TITLE
Episcanpy is incompatible with anndata 0.7.1

### ISSUE THREAD

**Issue by le-ander** [colomemaria/epiScanpy#51]
Hi Anna,

I just stumbled over another problem with episcanpy. With the latest anndata version installed (0.7.1), I cannot import episcanpy 0.1.8 anymore.

I get the following error:
```python
Python 3.7.5 (default, Dec 22 2019, 13:37:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import episcanpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leander.dony/.local/lib/python3.7/site-packages/episcanpy/__init__.py", line 18, in <module>
    check_versions()
  File "/home/leander.dony/.local/lib/python3.7/site-packages/episcanpy/utils.py", line 34, in check_versions
    if anndata.__version__ < LooseVersion('0.6.10'):
  File "/app/python37/lib/python3.7/distutils/version.py", line 64, in __gt__
    c = self._cmp(other)
  File "/app/python37/lib/python3.7/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'Version' object has no attribute 'version'
```
This does not occur with anndata 0.6.22.post1

Would be great if episcanpy would soon be compatible with anndata again :)

**Comment by le-ander** [comment]
This has been fixed in c37343b80703f2a9201a8f885742e20104cc944c
