### ISSUE TITLE
Error of version 0.2.0+7.g709bba8

### ISSUE THREAD

**Issue by kridsadakorn** [colomemaria/epiScanpy#70]
episcanpy version 0.2.0+7.g709bba8
There is the error when import the library

```
>>> import episcanpy
/opt/miniconda3/envs/episcanpy/lib/python3.6/site-packages/scanpy/api/__init__.py:7: FutureWarning: 

In a future version of Scanpy, `scanpy.api` will be removed.
Simply use `import scanpy as sc` and `import scanpy.external as sce` instead.

  FutureWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/episcanpy/lib/python3.6/site-packages/episcanpy/__init__.py", line 25, in <module>
    from . import tools as tl
  File "/opt/miniconda3/envs/episcanpy/lib/python3.6/site-packages/episcanpy/tools/__init__.py", line 12, in <module>
    from scanpy.api.tl import dpt
  File "/opt/miniconda3/envs/episcanpy/lib/python3.6/site-packages/scanpy/api/__init__.py", line 27, in <module>
    from . import pl
  File "/opt/miniconda3/envs/episcanpy/lib/python3.6/site-packages/scanpy/api/pl.py", line 1, in <module>
    from ..plotting._anndata import scatter, violin, ranking, clustermap, stacked_violin, heatmap, dotplot, matrixplot, tracksplot
ImportError: cannot import name 'stacked_violin'

```

Some configurations might be missing?

**Comment by DaneseAnna** [comment]
Hum, I am not sure why it does that. stacked_violin should be imported but it is a reported issue in scanpy as well. https://github.com/theislab/scanpy/issues/1397
Apparently downgrading scanty to 1.5.1 fix the problem for now.
I will have a closer look but if you find the solution, let me know.
